# Sentiment Vectorization: Bag of Words vs TF-IDF

This notebook demonstrates sentiment analysis using two text vectorization techniques:
- **Bag of Words (BoW)**: Simple word frequency counting
- **TF-IDF**: Term Frequency - Inverse Document Frequency

We'll compare how these methods represent the same sentiment data differently.

## Section 1: Import Required Libraries

In [1]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
import pandas as pd
import numpy as np

print("✓ Libraries imported successfully!")

✓ Libraries imported successfully!


## Section 2: Load and Prepare Dataset

Our dataset contains 4 movie review samples with different sentiments (positive and negative).

In [2]:
# Dataset: Sentiment samples
sentiments = [
    "I love this movie",
    "This movie is terrible",
    "Amazing acting",
    "Worst film ever"
]

# Display the dataset
print("📊 Sentiment Dataset:")
print("=" * 50)
for i, sentiment in enumerate(sentiments, 1):
    print(f"{i}. {sentiment}")
print("=" * 50)

📊 Sentiment Dataset:
1. I love this movie
2. This movie is terrible
3. Amazing acting
4. Worst film ever


## Section 3: Apply Bag of Words Vectorization

Bag of Words simply counts the frequency of each word in the documents. It ignores word order and emphasis.

In [3]:
# Apply Bag of Words Vectorization
bow_vectorizer = CountVectorizer()
bow_matrix = bow_vectorizer.fit_transform(sentiments)
bow_vocabulary = bow_vectorizer.get_feature_names_out()

print("🎒 Bag of Words Vectorization Applied!")
print(f"Matrix shape (documents × features): {bow_matrix.shape}")
print(f"Number of unique words: {len(bow_vocabulary)}")
print(f"Vocabulary: {list(bow_vocabulary)}")
print(f"\nBag of Words Matrix (Sparse Format):\n{bow_matrix}")

🎒 Bag of Words Vectorization Applied!
Matrix shape (documents × features): (4, 10)
Number of unique words: 10
Vocabulary: ['acting', 'amazing', 'ever', 'film', 'is', 'love', 'movie', 'terrible', 'this', 'worst']

Bag of Words Matrix (Sparse Format):
<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 12 stored elements and shape (4, 10)>
  Coords	Values
  (0, 5)	1
  (0, 8)	1
  (0, 6)	1
  (1, 8)	1
  (1, 6)	1
  (1, 4)	1
  (1, 7)	1
  (2, 1)	1
  (2, 0)	1
  (3, 9)	1
  (3, 3)	1
  (3, 2)	1


## Section 4: Apply TF-IDF Vectorization

TF-IDF (Term Frequency - Inverse Document Frequency) weights words by their importance. Common words across many documents get lower weights, while rare but meaningful words get higher weights.

In [4]:
# Apply TF-IDF Vectorization
tfidf_vectorizer = TfidfVectorizer()
tfidf_matrix = tfidf_vectorizer.fit_transform(sentiments)
tfidf_vocabulary = tfidf_vectorizer.get_feature_names_out()

print("📈 TF-IDF Vectorization Applied!")
print(f"Matrix shape (documents × features): {tfidf_matrix.shape}")
print(f"Number of unique words: {len(tfidf_vocabulary)}")
print(f"Vocabulary: {list(tfidf_vocabulary)}")
print(f"\nTF-IDF Matrix (Sparse Format):\n{tfidf_matrix}")

📈 TF-IDF Vectorization Applied!
Matrix shape (documents × features): (4, 10)
Number of unique words: 10
Vocabulary: ['acting', 'amazing', 'ever', 'film', 'is', 'love', 'movie', 'terrible', 'this', 'worst']

TF-IDF Matrix (Sparse Format):
<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 12 stored elements and shape (4, 10)>
  Coords	Values
  (0, 5)	0.66767854460954
  (0, 8)	0.5264054336099157
  (0, 6)	0.5264054336099157
  (1, 8)	0.43779123108611473
  (1, 6)	0.43779123108611473
  (1, 4)	0.5552826649411127
  (1, 7)	0.5552826649411127
  (2, 1)	0.7071067811865476
  (2, 0)	0.7071067811865476
  (3, 9)	0.5773502691896257
  (3, 3)	0.5773502691896257
  (3, 2)	0.5773502691896257


## Section 5: Print and Compare Matrices

Here we convert the sparse matrices to dense arrays and display them side-by-side for comparison.

In [5]:
# Convert sparse matrices to dense for better visualization
bow_dense = bow_matrix.toarray()
tfidf_dense = tfidf_matrix.toarray()

print("=" * 80)
print("📊 BAG OF WORDS MATRIX (Dense Format)")
print("=" * 80)
print(f"Vocabulary: {list(bow_vocabulary)}")
print(f"\nMatrix values:\n{bow_dense}")
print(f"\nMatrix shape: {bow_dense.shape} (4 documents × {len(bow_vocabulary)} features)")

print("\n" + "=" * 80)
print("📊 TF-IDF MATRIX (Dense Format)")
print("=" * 80)
print(f"Vocabulary: {list(tfidf_vocabulary)}")
print(f"\nMatrix values:\n{tfidf_dense}")
print(f"\nMatrix shape: {tfidf_dense.shape} (4 documents × {len(tfidf_vocabulary)} features)")

print("\n" + "=" * 80)
print("🔍 COMPARISON ANALYSIS")
print("=" * 80)
print(f"\n1. Bag of Words - Uses raw word counts")
print(f"   - Range: {bow_dense.min():.2f} to {bow_dense.max():.2f}")
print(f"   - Sum per document: {bow_dense.sum(axis=1)}")
print(f"\n2. TF-IDF - Uses normalized weighted scores")
print(f"   - Range: {tfidf_dense.min():.4f} to {tfidf_dense.max():.4f}")
print(f"   - Sum per document: {tfidf_dense.sum(axis=1)}")
print(f"\nKey Difference: TF-IDF penalizes common words and emphasizes rare, important terms.")

📊 BAG OF WORDS MATRIX (Dense Format)
Vocabulary: ['acting', 'amazing', 'ever', 'film', 'is', 'love', 'movie', 'terrible', 'this', 'worst']

Matrix values:
[[0 0 0 0 0 1 1 0 1 0]
 [0 0 0 0 1 0 1 1 1 0]
 [1 1 0 0 0 0 0 0 0 0]
 [0 0 1 1 0 0 0 0 0 1]]

Matrix shape: (4, 10) (4 documents × 10 features)

📊 TF-IDF MATRIX (Dense Format)
Vocabulary: ['acting', 'amazing', 'ever', 'film', 'is', 'love', 'movie', 'terrible', 'this', 'worst']

Matrix values:
[[0.         0.         0.         0.         0.         0.66767854
  0.52640543 0.         0.52640543 0.        ]
 [0.         0.         0.         0.         0.55528266 0.
  0.43779123 0.55528266 0.43779123 0.        ]
 [0.70710678 0.70710678 0.         0.         0.         0.
  0.         0.         0.         0.        ]
 [0.         0.         0.57735027 0.57735027 0.         0.
  0.         0.         0.         0.57735027]]

Matrix shape: (4, 10) (4 documents × 10 features)

🔍 COMPARISON ANALYSIS

1. Bag of Words - Uses raw word counts


## Section 6: Visualize Results with Pandas DataFrame

Convert both vectorization results into pandas DataFrames for easy visualization and comparison.

In [6]:
# Create DataFrames for visualization
df_bow = pd.DataFrame(
    bow_dense,
    columns=bow_vocabulary,
    index=[f"Review {i+1}" for i in range(len(sentiments))]
)

df_tfidf = pd.DataFrame(
    tfidf_dense,
    columns=tfidf_vocabulary,
    index=[f"Review {i+1}" for i in range(len(sentiments))]
)

print("📑 BAG OF WORDS - Pandas DataFrame")
print("=" * 80)
print(df_bow)
print(f"\nDataFrame Info:")
print(f"Shape: {df_bow.shape}")
print(f"Data Type: {df_bow.dtypes.unique()[0]}")

print("\n" + "=" * 80)
print("📑 TF-IDF - Pandas DataFrame")
print("=" * 80)
print(df_tfidf)
print(f"\nDataFrame Info:")
print(f"Shape: {df_tfidf.shape}")
print(f"Data Type: {df_tfidf.dtypes.unique()[0]}")

# Add sentiment labels for reference
df_results = pd.DataFrame({
    'Review': sentiments,
    'Index': [f"Review {i+1}" for i in range(len(sentiments))]
})

print("\n" + "=" * 80)
print("📋 SENTIMENT SAMPLES")
print("=" * 80)
print(df_results.to_string(index=False))

📑 BAG OF WORDS - Pandas DataFrame
          acting  amazing  ever  film  is  love  movie  terrible  this  worst
Review 1       0        0     0     0   0     1      1         0     1      0
Review 2       0        0     0     0   1     0      1         1     1      0
Review 3       1        1     0     0   0     0      0         0     0      0
Review 4       0        0     1     1   0     0      0         0     0      1

DataFrame Info:
Shape: (4, 10)
Data Type: int64

📑 TF-IDF - Pandas DataFrame
            acting   amazing     ever     film        is      love     movie  \
Review 1  0.000000  0.000000  0.00000  0.00000  0.000000  0.667679  0.526405   
Review 2  0.000000  0.000000  0.00000  0.00000  0.555283  0.000000  0.437791   
Review 3  0.707107  0.707107  0.00000  0.00000  0.000000  0.000000  0.000000   
Review 4  0.000000  0.000000  0.57735  0.57735  0.000000  0.000000  0.000000   

          terrible      this    worst  
Review 1  0.000000  0.526405  0.00000  
Review 2  0.55528

## Summary & Conclusions

### Key Takeaways

1. **Bag of Words (BoW)**
   - Simple word counting method
   - Easy to understand and implement
   - No consideration of word importance
   - Values: Raw counts (integers)

2. **TF-IDF (Term Frequency - Inverse Document Frequency)**
   - Weights words by their importance
   - Penalizes common words across documents
   - Emphasizes unique, meaningful terms
   - Values: Normalized weights (decimals between 0-1)

3. **When to Use**
   - **BoW**: Simple applications, baseline models
   - **TF-IDF**: Information retrieval, text classification, semantic search

### Observations from Our Dataset
- Both methods identify the same vocabulary
- TF-IDF weights differ across documents based on word frequency
- BoW emphasis on raw counts can be biased toward longer documents
- TF-IDF normalization makes different documents more comparable